# Generated by Django 3.0.3 on 2020-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0004_learnmore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmore',
            name='image',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
