# Generated by Django 3.0.3 on 2020-03-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0005_auto_20200313_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmore',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
